MBRAT_PROG='mbrat'
MBRAT_VER='0.2a'
MBRAT_PYVER='2.7'
DEF_COMMANDD='/usr/local/bin'
DEF_ROOTD='/home/notroot/Dev/python/mandelbrat/mbrat'
DEF_MAINF='/home/notroot/Dev/python/mandelbrat/mbrat/mbrat.py'
DEF_USRD='/home/notroot/Dev/python/mandelbrat/mbrat/usr'
DEF_CONFD='/home/notroot/Dev/python/mandelbrat/mbrat/mbratrc.d'
