MBRAT_PROG='mbrat'
MBRAT_VER='0.2a'
MBRAT_PYVER='2.7'
DEF_COMMANDD='/usr/local/bin'
DEF_ROOTD='/home/notroot/Dev/python/mbrat/mandelbrat'
DEF_MAINF='/home/notroot/Dev/python/mbrat/mandelbrat/mbrat.py'
DEF_USRD='/home/notroot/Dev/python/mbrat/mandelbrat/usr'
DEF_CONFD='/home/notroot/Dev/python/mbrat/mandelbrat/mbratrc.d'
